# Generated by Django 3.0.7 on 2020-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_auto_20200611_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=3),
        ),
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.ManyToManyField(blank=True, null=True, to='surveyapp.Answer'),
        ),
    ]
