# Generated by Django 3.0.7 on 2020-06-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_auto_20200611_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ManyToManyField(blank=True, to='surveyapp.Answer'),
        ),
    ]
