# Generated by Django 3.0.7 on 2020-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_auto_20200611_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ManyToManyField(blank=True, to='surveyapp.Question'),
        ),
    ]
