# Generated by Django 3.0.7 on 2020-06-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0005_auto_20200611_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ques',
        ),
        migrations.AddField(
            model_name='answer',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveyapp.Question'),
        ),
    ]
